/**:
  ros__parameters:
    cmd_freq: 100.0  # Hz (default: 100.0)
    info_freq: 10.0  # Hz (default: 10.0)
    mass: 0.82  # Kg
    max_thrust: 16.7  # N
    min_thrust: 0.15  # N
    control_modes_file: "/home/rafa/aerostack2_ws/src/aerostack2/stack/hardware_interface/pixhawk_platform/config/control_modes.yaml"  # (default: config/control_modes.yaml)